#Ne pas toucher permet au plugin de fonctionner, MERCI ! Vous pouvez seulement toucher aux messages !
world:
  public:

  private:
depend:
  VoidGenerator: 
#Merci de mettre de § a la place des & pour les codes couleurs, MERCI !  
message:
  rank:
    rank1: "V.I.P"
    rank2: "V.I.P+"
    rank3: "V.I.P++"
    
  menu:
    items:
      create: "Créer un monde"
      teleport: "Se téléporter a votre monde"
      delete: "Supprimer votre monde"
      invite: "Ouvrir le menu de gestion d'invitation de votre monde"
      border: "Gérer la limite de votre map"
      gamemode: "Gérer le mode de jeu(Survie, Créatif)"
      time: "Gérer le mode le jour et la nuit"
      difficulty: "Gérer la difficulté"
      quit: "Quitter votre monde"
      day: "Jour"
      night: "Nuit"
      survival: "§aSurvie"
      creative: "§aCréatif"
      spectator: "§aSpectateur"
      adventure: "§aAdventure"
      invitefriend: "Inviter un ami"
      joinpublicworld: "Rejoindre un Monde en Public"
      setpublicworld: "Mettre votre monde en public"
      peacefull: "Paisible"
      easy: "Facile"
      normal: "Normal"
      hard: "Difficile"
      borderlimit1: "Mettre la limite de votre monde a 10 000 blocs"
      borderlimit2: "Mettre la limite de votre monde a 30 000 blocs"
      borderlimit3: "Mettre la limite de votre monde a 60 000 blocs"
      borderlimit4: "Mettre la limite de votre monde a 120 000 blocs"
      
    answerResponse:
      loading: "§2Votre Monde est en train de se charger"
      loadingsucces: "§2Votre Monde est charger vous pouvez le rejoindre"
      step1: "§2Étape 1 sur 3"
      step2: "§2Étape 2 sur 3"
      step3: "§2Étape 3 sur 3"
      public: "§2Votre monde est desormait publique"
      tpaccept: "§2Vous avez été Téléporter au monde"
      setday: "§2Le jour se lève"
      setnight: "§2Le soleil se couche"
      notInWorld: "§2Vous devez être dans votre monde"
      tp: "§2Vous avez été Téléporter dans votre monde"
      help: "§2Pour inviter des amis ou pour gerer votre monde /sc"
      quitworld: "§2Vous avez quitter votre monde"
      survival: "§2Vous êtes maintenant en survie"
      creative: "§2Vous êtes maintenant en Créatif"
      spectator: "§2Vous êtes maintenant en Spectateur"
      adventure: "§2Vous êtes maintenant en Aventure"
      invitefriendhelp: "§2Pour inviter un ami /scinvite (nom de la personne)"
      difficultychange: "§2La difficulté a été changé"
      deleteworld: "§2Votre monde est maintenant supprimé"
      borderset1: "§2La limite de votre monde est maintenant de 10 000 blocs"
      borderset2: "§2La limite de votre monde est maintenant de 30 000 blocs"
      borderset3: "§2La limite de votre monde est maintenant de 60 000 blocs"
      borderset4: "§2La limite de votre monde est maintenant de 120 000 blocs"
      nopermission: "§cVous n'avez pas la permission, venez l'acheter sur la boutique §6https://endide-shop.tebex.io/"
      worldExist: "§2Vous possédez deja un monde"