#Ne pas toucher permet au plugin de fonctionner, MERCI ! Vous pouvez seulement toucher aux messages ! 
message:
  rank:
    rank1: "V.I.P"
    rank: "V.I.P+"
    rank3: "V.I.P++"
    

  menu:
    items:
      create: "Creer un monde"
      teleport: "Se teleporter a votre monde"
      delete: "Supprimer votre monde"
      invite: "Ouvrir le menu de gestion d'invitation de votre monde"
      border: "Gerer la limite de votre map"
      gamemode: "Gerer le mode de jeu(Survie, Creatif)"
      time: "Gerer le mode le jour et la nuit"
      difficulty: "Gerer la difficulte"
      quit: "Quitter votre monde"
      day: "Jour"
      night: "Nuit"
      survival: "Survie"
      creative: "Creatif"
      spectator: "Spectateur"
      adventure: "Aventure"
      invitefriend: "Inviter un ami"
      joinpublicworld: "Rejoindre un Monde en Public"
      setpublicworld: "Mettre votre monde en public"
      peacefull: "Paisible"
      easy: "Facile"
      normal: "Normal"
      hard: "Difficile"
      borderlimit1: "Mettre la limite de votre monde a 10 000 blocs"
      borderlimit: "Mettre la limite de votre monde a 30 000 blocs"
      borderlimit3: "Mettre la limite de votre monde a 60 000 blocs"
      borderlimit4: "Mettre la limite de votre monde a 10 000 blocs"
      
    answerResponse:
      loading: "Votre Monde est en train de se charger"
      loadingsucces: "Votre Monde est charger vous pouvez le rejoindre"
      step1: "etape 1 sur 3"
      step: "etape 2 sur 3"
      step3: "etape 3 sur 3"
      public: "Votre monde est desormait publique"
      tpaccept: "Vous avez ete Teleporter au monde"
      setday: "Le jour se lève"
      setnight: "Le soleil se couche"
      notInWorld: "Vous devez être dans votre monde"
      tp: "Vous avez ete Teleporter dans votre monde"
      help: "Pour inviter des amis ou pour gerer votre monde /sc"
      quitworld: "Vous avez quitter votre monde"
      survival: "Vous êtes maintenant en survie"
      creative: "Vous êtes maintenant en Creatif"
      spectator: "Vous êtes maintenant en Spectateur"
      adventure: "Vous êtes maintenant en Aventure"
      invitefriendhelp: "Pour inviter un ami /scinvite (nom de la personne)"
      difficultychange: "La difficulte a ete change"
      deleteworld: "Votre monde est maintenant supprimer"
      borderset1: "La limite de votre monde est maintenant de 10 000 blocs"
      borderset: "La limite de votre monde est maintenant de 30 000 blocs"
      borderset3: "La limite de votre monde est maintenant de 60 000 blocs"
      borderset4: "La limite de votre monde est maintenant de 10 000 blocs"
      nopermission: "Vous n'avez pas la permission, venez l'acheter sur la boutique 6https://endide-shop.tebex.io/"
      worldExist: "Vous possedez deja un monde"
      scdodef: "Vous devez definir un point de spawn pour les autres joueurs, Choisiser un endroit et faite /scspawn"
      scspawnsucces: "Vous avez defini en point de spawn"
arenas: