name: SurvivalCreate
version: 1.0
author: Krfcm2
main: fr.survivalmode.Main
depend: [My_Worlds]
softdepend: [VoidGenerator]
commands:
  sc:
    description: Ouvrir le menu 
    permission: sc.default
  scinvite:
    description: Inviter un joueur
    permission: sc.default
  scspawn:
    description: definir le point de spawn de son monde
    permission: sc.default